import type { Question } from './types';

export const initialQuestions: Question[] = [
  {
    id: 1,
    question: 'Qual festival asiático é conhecido por celebrar a chegada da primavera com grandes batalhas de água nas ruas?',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'thailand festival',
    options: ['Festival das Lanternas', 'Songkran', 'Hanami', 'Diwali'],
    answer: 'Songkran',
    type: 'multiple-choice',
    difficulty: 'easy',
    category: 'Cultura',
    explanation: 'O Songkran é o Ano Novo Tailandês, celebrado com rituais de purificação e grandes batalhas de água, simbolizando a remoção do mal e a renovação.',
  },
  {
    id: 2,
    question: 'A expressão "Hakuna Matata", popularizada globalmente, origina-se de qual idioma?',
    options: ['Yoruba', 'Zulu', 'Swahili', 'Amárico'],
    answer: 'Swahili',
    type: 'multiple-choice',
    difficulty: 'easy',
    category: 'Idioma',
    explanation: '"Hakuna Matata" é uma frase em Swahili que significa "sem problemas". É falada em vários países da África Oriental.',
  },
  {
    id: 3,
    question: 'Na Finlândia, o sistema educacional é famoso por ter pouca ou nenhuma lição de casa.',
    options: ['Verdadeiro', 'Falso'],
    answer: 'Verdadeiro',
    type: 'true-false',
    difficulty: 'easy',
    category: 'Sistemas Educacionais',
    explanation: 'O modelo finlandês foca em aprendizado em sala de aula, mais tempo livre e menos estresse, sendo consistentemente classificado como um dos melhores do mundo.',
  },
  {
    id: 4,
    question: 'Qual destes pratos é um pilar da culinária etíope, servido sobre um pão achatado chamado Injera?',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'ethiopian food',
    options: ['Cuscus', 'Doro Wat', 'Feijoada', 'Paella'],
    answer: 'Doro Wat',
    type: 'multiple-choice',
    difficulty: 'medium',
    category: 'Cultura',
    explanation: 'Doro Wat, um ensopado de frango picante, é um dos pratos mais famosos da Etiópia. A Injera é usada tanto como prato quanto como talher.',
  },
  {
    id: 5,
    question: 'O "Gaokao" é um exame de admissão universitária notoriamente difícil em qual país?',
    options: ['Japão', 'Coreia do Sul', 'China', 'Singapura'],
    answer: 'China',
    type: 'multiple-choice',
    difficulty: 'medium',
    category: 'Sistemas Educacionais',
    explanation: 'O Gaokao é o exame nacional de admissão ao ensino superior da China. É conhecido por sua intensidade e é um momento decisivo para milhões de estudantes.',
  },
  {
    id: 6,
    question: 'O idioma japonês utiliza três sistemas de escrita diferentes: Hiragana, Katakana e Kanji.',
    options: ['Verdadeiro', 'Falso'],
    answer: 'Verdadeiro',
    type: 'true-false',
    difficulty: 'medium',
    category: 'Idioma',
    explanation: 'Hiragana para palavras nativas e gramática, Katakana para palavras estrangeiras e onomatopeias, e Kanji (caracteres de origem chinesa) para a maioria dos substantivos e radicais de verbos.',
  },
  {
    id: 7,
    question: 'O "Dia dos Mortos" é uma celebração vibrante e colorida originária de qual país?',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'mexico celebration',
    options: ['Espanha', 'Argentina', 'México', 'Portugal'],
    answer: 'México',
    type: 'multiple-choice',
    difficulty: 'easy',
    category: 'Cultura',
    explanation: 'Originário do México, o Día de los Muertos homenageia os entes queridos que já faleceram com altares, comidas, e festividades que celebram a vida.',
  },
  {
    id: 8,
    question: 'Qual sistema educacional é famoso por popularizar as "escolas na floresta", onde as crianças aprendem ao ar livre?',
    options: ['Suécia', 'Canadá', 'Dinamarca', 'Nova Zelândia'],
    answer: 'Dinamarca',
    type: 'multiple-choice',
    difficulty: 'hard',
    category: 'Sistemas Educacionais',
    explanation: 'A Dinamarca é pioneira no conceito de "skovbørnehaver" (jardins de infância na floresta), onde a educação infantil se baseia na exploração da natureza.',
  },
  {
    id: 9,
    question: 'A expressão idiomática "It\'s all Greek to me" em inglês significa que algo é incompreensível. Qual é o equivalente comum em português do Brasil?',
    options: ['"É chinês para mim"', '"É grego para mim"', '"É russo para mim"', '"É árabe para mim"'],
    answer: '"É grego para mim"',
    type: 'multiple-choice',
    difficulty: 'medium',
    category: 'Idioma',
    explanation: 'Assim como em inglês, a expressão "É grego para mim" é usada em português para indicar que algo é totalmente incompreensível.',
  },
  {
    id: 10,
    question: 'O Haka, uma dança tradicional, é associado a qual povo indígena?',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'maori dance',
    options: ['Samoanos', 'Aborígenes Australianos', 'Maori', 'Havaianos'],
    answer: 'Maori',
    type: 'multiple-choice',
    difficulty: 'medium',
    category: 'Cultura',
    explanation: 'O Haka é uma dança cerimonial do povo Maori da Nova Zelândia, famosa mundialmente pela sua performance pela equipe nacional de rugby, os All Blacks.',
  },
  {
    id: 11,
    question: 'As universidades de "Ivy League" estão localizadas nos Estados Unidos.',
    options: ['Verdadeiro', 'Falso'],
    answer: 'Verdadeiro',
    type: 'true-false',
    difficulty: 'easy',
    category: 'Sistemas Educacionais',
    explanation: 'A Ivy League é um grupo de oito universidades privadas de elite localizadas no nordeste dos Estados Unidos, como Harvard, Yale e Princeton.',
  },
  {
    id: 12,
    question: 'Qual é o idioma com o maior número de falantes nativos no mundo?',
    options: ['Inglês', 'Espanhol', 'Mandarim', 'Hindi'],
    answer: 'Mandarim',
    type: 'multiple-choice',
    difficulty: 'medium',
    category: 'Idioma',
    explanation: 'O Chinês Mandarim tem o maior número de falantes nativos, com mais de 900 milhões de pessoas.',
  },
  {
    id: 13,
    question: 'O carnaval do Rio de Janeiro é o único grande carnaval do mundo.',
    options: ['Verdadeiro', 'Falso'],
    answer: 'Falso',
    type: 'true-false',
    difficulty: 'easy',
    category: 'Cultura',
    explanation: 'Embora o do Rio seja um dos mais famosos, existem outras grandes celebrações de carnaval pelo mundo, como em Veneza (Itália), Nova Orleans (EUA) e Trinidad e Tobago.',
  },
  {
    id: 14,
    question: 'O conceito de "Bacharelado" e "Mestrado" faz parte de qual acordo de padronização do ensino superior na Europa?',
    options: ['Acordo de Schengen', 'Tratado de Lisboa', 'Processo de Bolonha', 'Erasmus+'],
    answer: 'Processo de Bolonha',
    type: 'multiple-choice',
    difficulty: 'hard',
    category: 'Sistemas Educacionais',
    explanation: 'O Processo de Bolonha visa criar um Espaço Europeu de Ensino Superior, padronizando a estrutura de graus (licenciatura/bacharelado, mestrado, doutorado) para facilitar a mobilidade acadêmica.',
  },
  {
    id: 15,
    question: 'O gesto de balançar a cabeça de um lado para o outro significa "não" em todas as culturas.',
    options: ['Verdadeiro', 'Falso'],
    answer: 'Falso',
    type: 'true-false',
    difficulty: 'medium',
    category: 'Cultura',
    explanation: 'Em alguns lugares, como na Bulgária e partes da Índia, este gesto pode significar "sim", o que pode causar bastante confusão.',
  },
  {
    id: 16,
    question: 'O Basco (Euskara), falado na Espanha e França, é um "idioma isolado", o que significa que não tem relação com nenhum outro idioma conhecido.',
    options: ['Verdadeiro', 'Falso'],
    answer: 'Verdadeiro',
    type: 'true-false',
    difficulty: 'hard',
    category: 'Idioma',
    explanation: 'A origem do Basco é um dos grandes mistérios da linguística, pois ele não compartilha uma ancestralidade comum com as línguas indo-europeias que o cercam.',
  },
  {
    id: 17,
    question: 'A cerimônia do chá é uma prática cultural de grande importância em qual país?',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'japanese tea',
    options: ['Índia', 'Japão', 'Inglaterra', 'Turquia'],
    answer: 'Japão',
    type: 'multiple-choice',
    difficulty: 'easy',
    category: 'Cultura',
    explanation: 'No Japão, a cerimônia do chá (Chadō ou Sadō) é uma arte tradicional que envolve a preparação e apresentação cerimonial do matcha, o chá verde em pó.',
  },
  {
    id: 18,
    question: 'Qual destes não é um sistema de escrita?',
    options: ['Cirílico', 'Arábico', 'Rúnico', 'Gramático'],
    answer: 'Gramático',
    type: 'multiple-choice',
    difficulty: 'easy',
    category: 'Idioma',
    explanation: '"Gramático" refere-se à gramática, o conjunto de regras de uma língua. Cirílico, Arábico e Rúnico são sistemas de escrita históricos ou atuais.',
  },
  {
    id: 19,
    question: 'O que é um "ano sabático", comum em sistemas educacionais como o do Reino Unido?',
    options: ['Um ano de estudos intensivos', 'Um ano de folga antes da universidade para viajar ou trabalhar', 'Um ano obrigatório de serviço militar', 'Um exame final do ensino médio'],
    answer: 'Um ano de folga antes da universidade para viajar ou trabalhar',
    type: 'multiple-choice',
    difficulty: 'medium',
    category: 'Sistemas Educacionais',
    explanation: 'O "gap year" ou ano sabático é uma pausa que muitos estudantes fazem para ganhar experiência de vida, trabalhar ou viajar antes de iniciar seus estudos universitários.',
  },
  {
    id: 20,
    question: 'O Festival de Diwali, conhecido como o "Festival das Luzes", é uma das celebrações mais importantes de qual religião?',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'hindu festival',
    options: ['Islamismo', 'Budismo', 'Cristianismo', 'Hinduísmo'],
    answer: 'Hinduísmo',
    type: 'multiple-choice',
    difficulty: 'hard',
    category: 'Cultura',
    explanation: 'Diwali é uma grande celebração no Hinduísmo, simbolizando a vitória da luz sobre as trevas e do bem sobre o mal. Também é celebrado por jainistas e sikhs.',
  },
];
